/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$all': RouteRecordInfo<'$all', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'legal-cookie-policy': RouteRecordInfo<'legal-cookie-policy', '/legal/cookie-policy', Record<never, never>, Record<never, never>>,
    'legal-privacy-policy': RouteRecordInfo<'legal-privacy-policy', '/legal/privacy-policy', Record<never, never>, Record<never, never>>,
    'legal-terms-and-conditions': RouteRecordInfo<'legal-terms-and-conditions', '/legal/terms-and-conditions', Record<never, never>, Record<never, never>>,
    'legal-terms-of-service': RouteRecordInfo<'legal-terms-of-service', '/legal/terms-of-service', Record<never, never>, Record<never, never>>,
  }
}
